### PR TITLE
Todolist-A Microverse mandatory project To put into practice JavaScript functional and the module ES6 syntax 

### PR DESCRIPTION
**Pull request by elisha2kyakpo1**
-IN this project a user can create a project.
-Inside the project, a user can create a todo project
-A user can see the created projects.
-A user can see the created todos when they click on a project in which a todo was created.
-A user can also delete a project or a todo.
-A user can also edit or mark a todo as completed.
-A user can select priority, from high to low.
-I have used localStorage to store data.

### CODE REVIEW

**Review by Forison — CHANGES_REQUESTED** [review]
## Status::Changes Required❌

# 👋 team

#### You have done a good job on this one so far, the code is well split into module, you added a validation feature, and code are all written the ES6 syntax, however there are some issues we have to address to get this approved.

* [ ] Pull request should have a title and a short description of what specifically was done on the current branch ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)).

* [ ] Your readme should contain an image of the page you have created, [Check Microverse Specification here]([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)))

* [ ] Kindly include the step to launch the application on a local machine, currently you only end at, `npx webpack --watch`, state explicitly what visitor ought to do after the this command to view the application in their browser.

* [ ] In my attempt to  create a new project I get this error in the console of my browser, Hence I am unable to create a project thereby unable to validate the other requirements.

aaa

* [ ] User can view all projects
* [ ] User can view all to-dos in each project
* [ ] User can edit the details of a to-do item
* [ ] User can delete a to-do


#### Projects ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/projects_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/todo-list))

* [ ] The application allows to have different projects (or separate lists of to-dos)
* [ ] There is a 'default' project
* [ ] The user can create new projects
* [ ] The user can assign a to-do list items to a project

#### To-do item / Task ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/todo_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/todo-list))

* [ ] It is an object
* [ ] It is generated dynamically (Either with a factory or a constructor)
* [ ] It has a title
* [ ] It has a description
* [ ] It has a due date
* [ ] It has a priority

#### That is it, kindly make the changes and submit a re-review 🦹‍♂️

#### Happy coding👨‍💻

Addo Forison

**Comment by elisha2kyakpo1** [comment]
I have made all the changes requested, if you find it difficult to run the project, find me on slack as Elisha kyakopo.
I can't see the error from here, maybe you didn't run npx webpack

**Comment by elisha2kyakpo1** [comment]
Also make sure that you checkout from development to todolist

**Review by rukundoeric — CHANGES_REQUESTED** [review]
# Status: ♻️ CHANGES REQUIRED ♻️
_Great job guys so far 👏 💯 👍. However, there are few issues we need to address before we move on, please check the comments below._

- ### To Highlight
  - [x] The code looks clean and professional. 💯
  - [x] The project follows Git flow. 💯

- ### To Improve
  - [ ] [MANDATORY] Necessary run common commands like build, development should be in package.json inside `scripts'. Here is a basic example ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/scripts_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622602/))
     - Ex: 
          ```json
          "scripts": {
            "dev": "webpack --mode development",
            "build": "webpack --mode production",
            "start": "webpack-dev-server --mode development --open" // optional
          }
  - [ ] [MANDATORY] Remove all commented codes
  - [ ] [MANDATORY] Your app is throwing an error when trying to create a project.  
     ![review-12](https://user-images.githubusercontent.com/45217364/115167469-06984080-a0b8-11eb-8b3f-101150808f6d.png)


_Please make all the required changes before you submit another code review. If you have any problems or concerns, you can reach out to me on Slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
Slack: Rukundo Eric**

**Review by NtwaliHeritier — APPROVED** [review]
### **STATUS: APPROVED✔✔✔**
Great implementation of the project👏👏👏

You can merge💻💻💻

**Comment by elisha2kyakpo1** [comment]
Thanks, @NtwaliHeritier .

**Pull request merged**
